language: python
cache: pip
dist: focal
matrix:
    fast_finish: true
    include:

      - { python: "3.8", env: DJANGO=4.0 }
      - { python: "3.8", env: DJANGO=4.1 }
      - { python: "3.8", env: DJANGO=4.2 }

      - { python: "3.9", env: DJANGO=4.0 }
      - { python: "3.9", env: DJANGO=4.1 }
      - { python: "3.9", env: DJANGO=4.2 }

      - { python: "3.10", env: DJANGO=4.0 }
      - { python: "3.10", env: DJANGO=4.1 }
      - { python: "3.10", env: DJANGO=4.2 }

      - { python: "3.11", env: DJANGO=4.0 }
      - { python: "3.11", env: DJANGO=4.1 }
      - { python: "3.11", env: DJANGO=4.2 }
install:
    - pip install tox tox-venv tox-travis
    - curl -sSL https://install.python-poetry.org | python3 -
    - source $HOME/.poetry/env
script:
    - tox
#after_success:
#    - pip install codecov
#    - codecov -e TOXENV,DJANGO
notifications:
    email: false